name: Simple Android Kernel Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v4
        with:
          repository: LineageOS/android_kernel_sony_sm8550
          fetch-depth: 0

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git ccache clang lld flex bison libssl-dev bc python3 libelf-dev

      - name: Clone mkbootimg and avbtool
        run: |
          git clone https://android.googlesource.com/platform/system/tools/mkbootimg mkbootimg_tools
          git clone https://android.googlesource.com/platform/external/avb avb_tools

      - name: Build Kernel
        env:
          ARCH: arm64
          CC: ccache clang
          HOSTCC: ccache clang
          LD: ld.lld
          HOST_LD: ld.lld
          OBJDUMP: llvm-objdump
          OBJCOPY: llvm-objcopy
          STRIP: llvm-strip
          O: out
        run: |
          # Create a directory for the output artifacts
          mkdir -p $O
          
          # Clean the source tree from previous builds
          make mrproper
          
          # Configure the kernel using the GKI defconfig
          make gki_defconfig
          
          # Start the actual kernel compilation, using all available CPU threads
          make -j$(nproc)
          
      - name: Create Boot Image
        run: |
          # Generate a dummy ramdisk for the boot image
          echo "DUMMY_RAMDISK" > ramdisk.img
          
          # Create the boot.img using the compiled kernel and dummy ramdisk
          python3 ./mkbootimg_tools/mkbootimg.py \
            --header_version 4 \
            --kernel ./out/arch/arm64/boot/Image \
            --ramdisk ./ramdisk.img \
            --output boot.img

      - name: Sign Boot Image
        run: |
          # Generate a dummy test key for signing
          python3 -c "import os, subprocess; os.makedirs('test_key', exist_ok=True); with open('test_key/private_key.pem', 'w') as f: f.write(subprocess.run(['openssl', 'genrsa', '2048'], capture_output=True, text=True).stdout)"
          
          # Sign the boot image with the generated key
          python3 ./avb_tools/avbtool.py add_hash_footer \
            --partition_name boot \
            --partition_size $((64 * 1024 * 1024)) \
            --image boot.img \
            --algorithm SHA256_RSA2048 \
            --key ./test_key/private_key.pem

      - name: Upload Boot Image
        uses: actions/upload-artifact@v4
        with:
          name: boot-image
          path: boot.img
